os: osx
osx_image: xcode8
language: cpp
compiler: clang
env:
        TOOLS=Autotools
script:
        - aclocal
        - automake --add-missing
        - autoconf || autoreconf
        - automake 
        - clang++ src/Sudoku-solver.cpp src/main.cpp -std=c++11 -o bin/ssolver
        - test-sudokus/solve-sudokus.sh
