os: osx
osx_image: xcode8
language: cpp
compiler: clang
env:
        TOOLS=Autotools
script:
        - mkdir bin
        - clang++ src/Sudoku-solver.cpp src/main.cpp -std=c++11 -o bin/ssolver
        - test-sudokus/solve-sudokus.sh

email: false
